import type { Device } from './types';

/**
 * Deterministic seeded RNG, ported line-for-line from the wireframe's own
 * `hashStr` / `mulberry32` / `rngFor` — SmartSecure has no live PostHog
 * project, so every number in this dashboard is generated by this
 * generator, keyed by a chart name + the current device filter, rather
 * than fetched from any backend.
 */
export function hashStr(s: string): number {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

export function mulberry32(a: number): () => number {
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function rngFor(key: string): () => number {
  return mulberry32(hashStr(key));
}

export function devFactor(dev: Device): number {
  return dev === 'ios' ? 0.58 : dev === 'android' ? 0.42 : 1;
}

/**
 * Scales cumulative counts (sessions, screen views, completions) to the
 * selected window length, relative to the 30-day baseline the seeded
 * sample series were built for. Rate/percentage metrics are window-
 * independent and must not be passed through this.
 */
export function rangeFactor(range: number): number {
  return range / 30;
}
