export const CD: Record<string, any> = {
  trend:{
    labels:[],
    multi:true,
    datasets:[],h:false,def:'bar'
  },
  tiers:{labels:[],values:[],colors:[],h:false,def:'doughnut'},
  rulecat:{labels:[],values:[],
    colors:[],h:false,def:'bar'},
  dailyfires:{
    labels:[],
    multi:true,
    datasets:[],
    h:false,def:'line'
  },
  tierdist:{labels:[],values:[],colors:[],h:false,def:'doughnut'},
  newmem:{labels:[],values:[],colors:[],h:false,def:'bar'},
  redtype:{labels:[],
    values:[],
    colors:[],h:false,def:'doughnut'},
  redtrend:{
    labels:[],
    multi:true,
    datasets:[],h:false,def:'line'
  },
  walletflow:{
    labels:[],
    multi:true,
    datasets:[],h:false,def:'bar'
  },
  orderage:{labels:[],values:[],
    colors:[],h:false,def:'bar'},
  orderstatus:{labels:[],values:[],
    colors:[],h:false,def:'doughnut'},
  funnel:{
    labels:[],
    multi:true,
    datasets:[],h:true,def:'bar'
  },
  catmix:{labels:[],values:[],
    colors:[],h:false,def:'doughnut'}
};

export const DRILLS: Record<string, string> = {
  'members-kpi':`<div class="flex gap-2 mb-3.5 flex-wrap"><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#2C2C2C]">2,847</div><div class="text-[9px] text-[#798C5E] mt-0.5">Total Active</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#BA7517]">385</div><div class="text-[9px] text-[#798C5E] mt-0.5">Gold</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#888780]">1,042</div><div class="text-[9px] text-[#798C5E] mt-0.5">Silver</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#C4B89D]">1,420</div><div class="text-[9px] text-[#798C5E] mt-0.5">Bronze</div></div></div><div class="text-[9px] font-bold uppercase tracking-wide text-[#798C5E] my-2">Breakdown</div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>New this month</span><span class="text-[#085041] font-bold">+124</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Lapsed (60+ days)</span><span class="text-[#A32D2D] font-bold">318</span></div><div class="flex justify-between items-center py-1.5 text-[11px]"><span>Avg points/member</span><span class="font-semibold">226 pts</span></div>`,
  'expired-points':`<div class="flex gap-2 mb-3.5 flex-wrap"><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#BA7517]">0</div><div class="text-[9px] text-[#798C5E] mt-0.5">Expired To Date</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#2C2C2C]">6,45,100</div><div class="text-[9px] text-[#798C5E] mt-0.5">Pts Outstanding</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#888780]">—</div><div class="text-[9px] text-[#798C5E] mt-0.5">Expiry Window</div></div></div><div class="text-[9px] font-bold uppercase tracking-wide text-[#798C5E] my-2">Why is this 0?</div><div class="p-2 bg-[#FFFAF0] rounded-[8px] border border-[#EDC488]/40 text-[11px] leading-relaxed text-[#2C2C2C]">No points have expired yet, but that number isn't fully trustworthy until the expiry window for this programme is confirmed. If no expiry policy is configured on the platform, points simply never lapse — which is a different (and riskier) situation than a policy that hasn't caught up yet. This needs sign-off from the dev team.</div>`,
  'redemption-kpi':`<div class="flex gap-2 mb-3.5 flex-wrap"><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#2C2C2C]">23.4%</div><div class="text-[9px] text-[#798C5E] mt-0.5">Rate</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#2C2C2C]">2,912</div><div class="text-[9px] text-[#798C5E] mt-0.5">Redemptions</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#2C2C2C]">12,450</div><div class="text-[9px] text-[#798C5E] mt-0.5">Eligible</div></div></div><div class="text-[9px] font-bold uppercase tracking-wide text-[#798C5E] my-2">Top Categories</div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Encashment</span><span class="font-bold text-[#085041]">1,240 (42.5%)</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Vouchers</span><span class="font-semibold">680 (23.3%)</span></div><div class="flex justify-between items-center py-1.5 text-[11px]"><span>Merchandise</span><span class="font-semibold">420 (14.4%)</span></div>`,
  'lapsed':`<div class="flex gap-2 mb-3.5 flex-wrap"><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#A32D2D]">318</div><div class="text-[9px] text-[#798C5E] mt-0.5">Lapsed Members</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#2C2C2C]">60+</div><div class="text-[9px] text-[#798C5E] mt-0.5">Days Inactive</div></div></div><div class="text-[9px] font-bold uppercase tracking-wide text-[#798C5E] my-2">Risk Breakdown</div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Bronze tier (highest risk)</span><span class="text-[#A32D2D] font-bold">224</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Silver tier</span><span class="text-[#BA7517] font-semibold">78</span></div><div class="flex justify-between items-center py-1.5 text-[11px]"><span>Gold tier</span><span class="text-[#085041] font-semibold">16</span></div>`,
  'rules-kpi':`<div class="flex gap-2 mb-3.5 flex-wrap"><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#2C2C2C]">34</div><div class="text-[9px] text-[#798C5E] mt-0.5">Active Rules</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#BA7517]">2</div><div class="text-[9px] text-[#798C5E] mt-0.5">Paused</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#888780]">1</div><div class="text-[9px] text-[#798C5E] mt-0.5">Draft</div></div></div><div class="text-[9px] font-bold uppercase tracking-wide text-[#798C5E] my-2">By Category</div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Collections</span><span>8</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Sales & Booking</span><span>7</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Referrals</span><span>6</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Possession</span><span>5</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Marketing Engagement</span><span>5</span></div><div class="flex justify-between items-center py-1.5 text-[11px]"><span>App Adoption</span><span>3</span></div>`,
  'stmt-lookup':`<div class="mb-3 text-[11px] text-[#798C5E]">Enter member ID, name, or phone to pull account statement.</div><input class="w-full font-[Poppins] text-[12px] border border-[#C4B89D] rounded-[8px] px-3 py-2 outline-none mb-2" placeholder="Search member…"><button class="w-full flex items-center justify-center gap-1.5 mt-2.5 py-2 px-3.5 bg-[#DA7756] text-white rounded-[8px] text-[11px] font-semibold cursor-pointer font-[Poppins] transition-opacity hover:opacity-90">📄 Pull Statement</button>`,
  'ledger-view':`<div class="text-[9px] font-bold uppercase tracking-wide text-[#798C5E] my-2">Recent Transactions</div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>19 Jun 11:42 · Rajesh Mehta</span><span class="text-[#085041] font-bold">+6,000</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>19 Jun 11:08 · Sunita Patel</span><span class="text-[#A32D2D] font-bold">-9,400</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>19 Jun 09:15 · Vikram Singh</span><span class="text-[#085041] font-bold">+250</span></div><div class="flex justify-between items-center py-1.5 text-[11px]"><span>18 Jun 16:30 · Anita Desai</span><span class="text-[#A32D2D] font-bold">-4,800</span></div>`,
  'orders-total':`<div class="flex gap-2 mb-3.5 flex-wrap"><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#2C2C2C]">52</div><div class="text-[9px] text-[#798C5E] mt-0.5">Total</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#085041]">45</div><div class="text-[9px] text-[#798C5E] mt-0.5">Fulfilled</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#A32D2D]">7</div><div class="text-[9px] text-[#798C5E] mt-0.5">Stuck</div></div></div><div class="text-[9px] font-bold uppercase tracking-wide text-[#798C5E] my-2">Order Age</div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>0-30 days</span><span class="font-semibold">38</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>31-60 days</span><span class="font-semibold">7</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>61-90 days</span><span>0</span></div><div class="flex justify-between items-center py-1.5 text-[11px]"><span>90+ days</span><span class="text-[#A32D2D] font-bold">7</span></div>`,
  'orders-stuck':`<div class="flex gap-2 mb-3.5 flex-wrap"><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#A32D2D]">7</div><div class="text-[9px] text-[#798C5E] mt-0.5">Stuck Orders</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#2C2C2C]">107</div><div class="text-[9px] text-[#798C5E] mt-0.5">Days — Oldest</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#085041]">100%</div><div class="text-[9px] text-[#798C5E] mt-0.5">Already Paid</div></div></div><div class="text-[9px] font-bold uppercase tracking-wide text-[#798C5E] my-2">Root Cause</div><div class="p-2 bg-[#F6F4EE] rounded-[6px] text-[10.5px] leading-relaxed">All 7 belong to customer Roshan Shetty, created 12–13 Mar 2026. Payment cleared and points were deducted, but order status was never advanced past Pending.</div>`,
  'orders-customer':`<div class="flex gap-2 mb-3.5 flex-wrap"><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#2C2C2C]">Roshan Shetty</div><div class="text-[9px] text-[#798C5E] mt-0.5">Customer</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#A32D2D]">7</div><div class="text-[9px] text-[#798C5E] mt-0.5">Stuck Orders</div></div></div><div class="text-[9px] font-bold uppercase tracking-wide text-[#798C5E] my-2">Order Total</div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Combined value</span><span class="font-bold">₹22,197</span></div><div class="flex justify-between items-center py-1.5 text-[11px]"><span>Date range</span><span>12–13 Mar 2026</span></div>`,
  'store-live':`<div class="flex gap-2 mb-3.5 flex-wrap"><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#A32D2D]">0</div><div class="text-[9px] text-[#798C5E] mt-0.5">Live in Store</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#085041]">3,235</div><div class="text-[9px] text-[#798C5E] mt-0.5">In Aggregator</div></div></div><div class="text-[9px] font-bold uppercase tracking-wide text-[#798C5E] my-2">By Category</div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Merchandise</span><span>0 of 3,165</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Lounge</span><span>0 of 62</span></div><div class="flex justify-between items-center py-1.5 text-[11px]"><span>Miles</span><span>0 of 8</span></div>`,
  'store-aggregator':`<div class="flex gap-2 mb-3.5 flex-wrap"><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#2C2C2C]">3,235</div><div class="text-[9px] text-[#798C5E] mt-0.5">Total Items</div></div></div><div class="text-[9px] font-bold uppercase tracking-wide text-[#798C5E] my-2">Available to Add</div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>🛍️ Merchandise</span><span class="text-[#085041] font-semibold">3,165 items</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>✈️ Lounge Access</span><span class="text-[#085041] font-semibold">62 items</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>🛫 Airline Miles</span><span class="text-[#085041] font-semibold">8 items</span></div><div class="flex justify-between items-center py-1.5 text-[11px]"><span>🎁 Gift Cards</span><span class="text-[#798C5E]">0 items</span></div>`,
  'store-empty-days':`<div class="flex gap-2 mb-3.5 flex-wrap"><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#BA7517]">27+</div><div class="text-[9px] text-[#798C5E] mt-0.5">Days Empty</div></div></div><div class="p-2 bg-[#FFFAF0] rounded-[8px] border border-[#EDC488]/40 text-[11px] leading-relaxed text-[#2C2C2C]">The store has had 0 live items since the programme went live. 12,400 points have been issued in that window with no redemption path — this is the single highest-priority fix on the programme.</div>`,
  'cat-merch':`<div class="flex gap-2 mb-3.5 flex-wrap"><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#2C2C2C]">3,165</div><div class="text-[9px] text-[#798C5E] mt-0.5">Available</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#A32D2D]">0</div><div class="text-[9px] text-[#798C5E] mt-0.5">Live</div></div></div><div class="p-2 bg-[#F6F4EE] rounded-[6px] text-[10.5px] leading-relaxed text-[#2C2C2C]">98% of all available inventory. Enough breadth to serve all 3 active members immediately — recommended starting category.</div>`,
  'cat-lounge':`<div class="flex gap-2 mb-3.5 flex-wrap"><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#2C2C2C]">62</div><div class="text-[9px] text-[#798C5E] mt-0.5">Available</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#A32D2D]">0</div><div class="text-[9px] text-[#798C5E] mt-0.5">Live</div></div></div><div class="p-2 bg-[#F6F4EE] rounded-[6px] text-[10.5px] leading-relaxed text-[#2C2C2C]">High-value, niche redemption. Airport lounges across multiple cities.</div>`,
  'cat-miles':`<div class="flex gap-2 mb-3.5 flex-wrap"><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#2C2C2C]">8</div><div class="text-[9px] text-[#798C5E] mt-0.5">Available</div></div><div class="bg-[#F6F4EE] rounded-[8px] p-2.5 flex-1 text-center min-w-[80px]"><div class="text-[18px] font-bold text-[#A32D2D]">0</div><div class="text-[9px] text-[#798C5E] mt-0.5">Live</div></div></div><div class="p-2 bg-[#F6F4EE] rounded-[6px] text-[10.5px] leading-relaxed text-[#2C2C2C]">Smallest category — airline mile transfer programmes.</div>`,
  'ord-1':`<div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Order ID</span><span class="font-semibold">ORD20260312-8032B</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Amount</span><span class="font-bold">₹660</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Customer</span><span>Roshan Shetty</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Created</span><span>12 Mar 2026</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Days Stuck</span><span class="text-[#A32D2D] font-bold">107</span></div>`,
  'ord-2':`<div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Order ID</span><span class="font-semibold">ORD20260312-C3DB</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Amount</span><span class="font-bold">₹6,203</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Customer</span><span>Roshan Shetty</span></div><div class="flex justify-between items-center py-1.5 border-b border-[#E0D8CC] text-[11px]"><span>Created</span><span>12 Mar 2026</span></div><div class="flex justify-between items-center py-1.5 text-[11px]"><span>Days Stuck</span><span class="text-[#A32D2D] font-bold">107</span></div>`
};

export const FALLBACKS: Record<string, string> = {
  trend: 'Points redeemed (40,800) represent only 32.8% of points issued (1,24,500) in June, and the redemption gap has widened every month since January. Launch a time-based rule that awards 300 bonus points to any member who redeems within 14 days of receiving a new credit — this directly narrows the gap.',
  tiers: '50% of members are Bronze tier, and all 318 lapsed members are concentrated in this cohort — indicating that Bronze members are not seeing enough value to stay engaged. Add a milestone rule awarding 500 points when a Bronze member reaches their 3rd payment, creating a clear upgrade pathway to Silver.',
  rulecat: 'Collections rules (4,120 fires) drive 31.7% of all rule activity, confirming that the early payment incentive is the highest-ROI programme component. App Adoption rules (780 fires) are the lowest — add a daily login streak rule to triple this category contribution.',
  tierdist: 'Bronze tier holds 50% of members (1,420) and contains 224 of the 318 lapsed members, a 15.8% lapse rate vs 4% for Silver. Create a time-based re-engagement rule that delivers 200 bonus points to any Bronze member inactive for 30 days via push notification.',
  redtype: 'Encashment dominates at 42.5% of all redemptions, creating concentration risk if cash flow tightens. Promote Experiences and Lounge Access (combined 10%) with a limited-time 1.5× point multiplier on these categories to diversify the redemption mix.',
  redtrend: 'Redemption rate improved from 8.4% in January to 23.4% in June, averaging +2.5 percentage points per month — at this pace the 30% target is 3 months away. Add personalised push notifications when a member accumulates enough points for their preferred redemption category to close the gap faster.',
  walletflow: 'The cumulative outstanding balance has grown to 6,45,100 points — 5.2× the monthly issuance rate — and if all points were redeemed simultaneously it would represent ₹6,45,100 in encashment liability. Run a targeted "Redeem Now" campaign for the 1,042 Silver members with balances above 2,000 points to reduce the liability pool by an estimated 20%.',
  orderage: 'All 7 stuck orders sit in the 90+ day bucket and belong to a single customer, Roshan Shetty, created in a 2-day window (12-13 Mar) — no other order from any period or customer is stuck. This is a one-time fulfilment failure, not a systemic gap. Push all 7 through fulfilment now without re-verifying payment, since all 7 are already Paid.',
  orderstatus: '86.5% of orders (45 of 52) complete normally, and the stuck 13.5% all have payment already cleared — this is a fulfilment follow-up gap, not a payment issue. Assign a team member to close out the 7 Roshan Shetty orders this week to prevent the pattern from repeating with future customers.',
  funnel: 'All three categories — Merchandise (3,165), Lounge (62), and Miles (8) — pass step 1 identically and fail at step 2, confirming this is one blocked workflow step, not three separate content gaps. Unblock the single "Add to Store" action once and all 3,235 items become available simultaneously.',
  catmix: 'Merchandise makes up 97.8% of available inventory (3,165 of 3,235 items) — more than enough breadth to serve all 3 active members immediately. Add Merchandise items first as a 50-100 item test batch, then expand to Lounge and Miles once verified working.'
};

export const getBotFallback = (q: string) => {
  const l = q.toLowerCase();
  if (l.includes('rules') || l.includes('fired')) return 'Collections rules fired 4,120 times this month — the highest of any category — confirming that the early payment incentive is working. 2 rules are currently paused (Birthday Bonus and one Referral rule). Reactivate the Birthday Bonus rule now to capture the 38 members with birthdays this month before the opportunity passes.';
  if (l.includes('expir') || l.includes('risk')) return 'No points have expired to date, but that number needs a caveat: the expiry window for this programme hasn\'t been confirmed with the dev team yet, so it isn\'t clear whether 0 means "nothing has lapsed yet" or "no expiry policy exists." Confirm the expiry configuration first — 6,45,100 points are outstanding and the answer changes how much of that is actually at risk.';
  if (l.includes('redemption') || l.includes('redeem')) return 'Redemption rate is 23.4% this month — up from 8.4% in January, a 2.8× improvement in 6 months. 42.5% of redemptions are encashments (1,240 redemptions), which means members prefer cash over products. Promote the Travel & Ticketing category (only 9.6%) with a 1.5× bonus to diversify the redemption mix and reduce encashment pressure.';
  if (l.includes('tier') || l.includes('gold') || l.includes('silver')) return 'Gold tier has 385 members (13.5%), Silver 1,042 (36.6%), and Bronze 1,420 (50%). All 318 lapsed members are concentrated in Bronze — a 22.3% lapse rate for that tier. Add a milestone rule giving 500 bonus points at the 3rd payment to create a clear Bronze-to-Silver upgrade pathway.';
  if (l.includes('top earn') || l.includes('earner')) return 'Top earner this month is Rajesh Mehta with 18,400 points earned, followed by Priya Sharma at 16,200. Both are Gold tier members using the 2× multiplier rule. Sunita Patel earned and fully redeemed 9,400 points in the same month — she is your highest-engagement member and the best candidate for a referral programme outreach.';
  if (l.includes('today') || l.includes('attention') || l.includes('action')) return '3 things need attention today: 42 pending encashments worth ₹2.1L are awaiting processing, 12 new encashments arrived this morning. 318 lapsed members have not been targeted with any re-engagement rule. Birthday Bonus rule is paused and 38 members have birthdays this month. Process the pending encashments first — customers waiting on cash payouts are your highest churn risk.';
  return "Your programme is performing well with 2,847 active members and 34 live rules. The biggest opportunity right now is the 318 lapsed Bronze members and the 42 pending encashments worth ₹2.1L. Try asking: which rules fired most today, why is redemption rate low, or what needs attention today.";
};
