import React from "react";

interface Enhancement {
  id: number;
  name: string;
  current: string;
  enhanced: string;
  type: string;
  effort: "S" | "M" | "H" | "VH";
  impact: "L" | "M" | "H" | "VH";
  priority: "P0" | "P1" | "P2" | "P3";
  owner: string;
}

const enhancements: Enhancement[] = [
  { id: 1, name: "Pre-Authorised Visitor Management", current: "Resident manually adds visitor name, phone, and visit date/time", enhanced: "AI auto-fills visitor details from past visits; NLP understands 'add my usual cleaner for Monday morning' voice command; auto-suggests approval/denial based on visit history pattern", type: "AI + NLP", effort: "M", impact: "H", priority: "P0", owner: "Product / AI Team" },
  { id: 2, name: "Unexpected Visitor Management", current: "Guard captures visitor photo and details; resident approves via IVR/push", enhanced: "AI face-matching against watchlist at gate; auto-denial for flagged individuals with instant admin alert; push notification shows visitor photo before approval", type: "AI + CV", effort: "M", impact: "VH", priority: "P0", owner: "Security / AI Team" },
  { id: 3, name: "OTP-Based Visitor Authentication", current: "System generates OTP sent to visitor's phone; guard validates", enhanced: "Time-limited QR code on visitor's phone instead of OTP; QR scanned by guard app with visual confirmation; OTP as fallback for no-data scenarios", type: "MCP (WhatsApp Business API)", effort: "S", impact: "H", priority: "P1", owner: "Product" },
  { id: 4, name: "IVR Calls / Push Notification Approval", current: "Pre-configured IVR and push sent to resident for approval", enhanced: "Smart routing: prefer push notification first → IVR only if unread in 60 seconds → escalate to family member if no response in 3 minutes; fully configurable timeout chain", type: "AI (Routing Logic)", effort: "S", impact: "H", priority: "P0", owner: "Platform" },
  { id: 5, name: "Digital Gate Pass", current: "System-generated pass stored in app", enhanced: "Digital gate pass as a scannable QR code in resident's Apple Wallet / Google Wallet; pass auto-expires at visit end time; no app open required at gate", type: "MCP (Apple Wallet / Google Wallet)", effort: "M", impact: "H", priority: "P1", owner: "Integrations" },
  { id: 6, name: "Goods In/Out Movement Tracing", current: "Guard manually logs goods details with item description", enhanced: "ANPR-linked goods entry: vehicle plate auto-captured; AI reads delivery note/invoice image uploaded by guard to auto-fill item details; weight sensor integration for DG fuel delivery", type: "AI + ANPR + CV", effort: "H", impact: "VH", priority: "P1", owner: "Integrations" },
  { id: 7, name: "Digital Logs", current: "All entry/exit stored in database; downloadable as CSV", enhanced: "Natural language log search: 'Show me all visitors from last week between 6–9pm'; auto-generate PDF audit report for any period; anomaly detection flagging unusual visit patterns", type: "AI (NLP + Anomaly Detection)", effort: "M", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 8, name: "Quick Visitor Categories", current: "One-tap visitor creation for common types", enhanced: "AI learns resident's most-used visitor types and pre-loads them; smart prediction: 'Your regular grocery delivery is likely arriving — add them?' based on time and day patterns", type: "AI (Prediction)", effort: "S", impact: "M", priority: "P2", owner: "AI Team" },
  { id: 9, name: "Voice Command Entry", current: "Guard logs visitor via voice", enhanced: "Multilingual voice command (Hindi, Arabic, Marathi, Tamil); offline-capable voice processing for no-connectivity zones; voice-to-structured-data auto-fill with guard confirmation step", type: "AI (STT + NLP) + Offline", effort: "H", impact: "H", priority: "P1", owner: "AI / Platform" },
  { id: 10, name: "Favourite Visitor", current: "Resident manually marks visitor as favourite", enhanced: "AI auto-suggests frequent visitors for favourite status; one-tap recurring invite scheduling ('Add John every Friday 10am–12pm for next 3 months')", type: "AI", effort: "S", impact: "M", priority: "P2", owner: "Product" },
  { id: 11, name: "Overstay Alerts", current: "Manual alert triggered when visitor exceeds approved time", enhanced: "AI extends alert window intelligently based on visit type (contractor gets 30 min grace; social visitor gets 5 min warning); auto-resend to resident at escalating intervals", type: "AI", effort: "S", impact: "H", priority: "P1", owner: "Platform" },
  { id: 12, name: "Pre-Authorised Cab Entry", current: "Resident pre-approves cab before arrival", enhanced: "Ola/Uber/Rapido API integration: resident shares ride with gate → cab registration auto-populates from ride-sharing app; no manual entry needed", type: "MCP (Ola / Uber API)", effort: "M", impact: "H", priority: "P0", owner: "Integrations" },
  { id: 13, name: "Frequent Visitor Pass", current: "System-issued pass for repeat visitors", enhanced: "Dynamic pass with facial recognition at gate for passholders; pass validity auto-renewed if visit cadence continues; expired pass sends renewal nudge to resident", type: "AI + CV", effort: "M", impact: "H", priority: "P1", owner: "AI / Security" },
  { id: 14, name: "Temperature Capture", current: "Guard manually enters temperature reading", enhanced: "IoT thermal camera auto-captures temperature at gate and logs to visitor record; anomaly alert if temperature above threshold; no manual guard action required", type: "IoT (Thermal Camera)", effort: "H", impact: "M", priority: "P2", owner: "IoT Team" },
  { id: 15, name: "Mask Check", current: "Guard visually verifies mask compliance", enhanced: "Computer vision at gate camera auto-detects mask/no-mask in real time; guard app notified only on non-compliance; audit log of all violations", type: "CV / AI", effort: "M", impact: "M", priority: "P2", owner: "AI Team" },
  { id: 16, name: "Seeking Invite", current: "Visitor sends invite request to resident", enhanced: "WhatsApp-based seek invite: visitor sends a message to a community WhatsApp number → system routes to resident for approval without visitor needing the app; seamless for first-time visitors", type: "MCP (WhatsApp Business)", effort: "S", impact: "H", priority: "P1", owner: "Integrations" },
  { id: 17, name: "Group Visitor Entry", current: "Guard manually logs group", enhanced: "Bulk QR code for events: one QR code per event covers all registered group members; each member scans on arrival for individual log entry; integrates with events module", type: "MCP (Events Module)", effort: "S", impact: "H", priority: "P1", owner: "Product" },
  { id: 18, name: "e-Intercom", current: "App-based call between resident and guard/visitor", enhanced: "WebRTC HD video intercom within app; supports video preview of gate camera before resident picks up; call archived for 24 hours for missed-call replay", type: "WebRTC + CV", effort: "M", impact: "H", priority: "P0", owner: "Platform" },
  { id: 19, name: "Pre-Approvals for Exit of Children", current: "Resident pre-authorises adults for child exit", enhanced: "AI prompts resident to update child exit approvals before school year/holiday; cross-references against registered family members; real-time alert if unapproved adult attempts exit", type: "AI + Alerts", effort: "S", impact: "VH", priority: "P0", owner: "Product / Safety" },
  { id: 20, name: "Child Safety Alert", current: "Alert on unapproved child exit", enhanced: "Computer vision identifies child + accompanying adult at exit point; auto-matches adult face to approved list; guard app vibrates with photo if mismatch; instant resident push", type: "CV + AI", effort: "H", impact: "VH", priority: "P0", owner: "AI / Security" },
  { id: 21, name: "Panic Button", current: "Resident/guard triggers security alert", enhanced: "Panic button triggers: (1) alert to all guards + admin simultaneously, (2) activates nearest CCTV camera recording, (3) auto-dials community security head via IVR, (4) logs GPS location of trigger", type: "MCP (CCTV) + IVR", effort: "M", impact: "VH", priority: "P0", owner: "Security" },
  { id: 22, name: "Resident-to-Resident Calling", current: "In-app call without sharing phone numbers", enhanced: "End-to-end encrypted WebRTC calls; voicemail with transcription when recipient is unavailable; call history within app; option to block specific residents", type: "WebRTC + AI (Transcription)", effort: "M", impact: "H", priority: "P1", owner: "Platform" },
  { id: 23, name: "Leave at Gate", current: "Resident authorises gate to hold item", enhanced: "Digital acknowledgement chain: guard scans item barcode/photo → resident notified → item stored in digital log → resident notified again when collected; integrates with mailroom module", type: "Other (Mailroom Integration)", effort: "S", impact: "H", priority: "P1", owner: "Product" },
  { id: 24, name: "Request Visit Code", current: "Resident generates time-limited entry code", enhanced: "Deep link visit code shareable via WhatsApp/SMS: recipient clicks link → auto-registers as visitor → code validates at gate; no app required for visitor", type: "MCP (Deep Link + WhatsApp)", effort: "S", impact: "H", priority: "P1", owner: "Integrations" },
  { id: 25, name: "Offline Mode (Guard App)", current: "Guard app works on cached data in no-network zones", enhanced: "Progressive sync: guard app syncs in last-known good state; all entry/exit events queued locally; batch-sync when connectivity restored; offline AI face-match against cached watchlist", type: "AI + Offline Sync", effort: "H", impact: "VH", priority: "P0", owner: "Platform" },
  { id: 26, name: "Staff Attendance", current: "Digital log with selfie", enhanced: "Geo-fenced selfie: selfie only accepted within GPS boundary of the community; liveness detection prevents photo spoofing; auto-flag if staff marks attendance outside permitted zone", type: "AI (Liveness + Geo)", effort: "M", impact: "H", priority: "P0", owner: "AI Team" },
  { id: 27, name: "Staff Access Management", current: "Configure wing/floor access per staff member", enhanced: "Role-based access integrated with physical access control (boom barrier/flap barrier); changes in app propagate to hardware in real time via API", type: "MCP (Access Control API)", effort: "M", impact: "H", priority: "P1", owner: "Integrations" },
  { id: 28, name: "Rule-Based Time Allocation", current: "Define entry/exit time windows per staff member", enhanced: "AI auto-suggests time windows based on historical attendance patterns; exception handling: resident can override for a specific day via app with reason log", type: "AI", effort: "S", impact: "M", priority: "P2", owner: "Product" },
  { id: 29, name: "Block / Red-Flag Staff", current: "Admin blocks staff community-wide", enhanced: "Propagates block to all communities on the platform for the same developer (shared blacklist); option to file formal complaint linked to police FIR number", type: "MCP (Cross-Community Sync)", effort: "M", impact: "VH", priority: "P0", owner: "Platform" },
  { id: 30, name: "Staff Entry/Exit Notification", current: "Push notification to resident on staff entry/exit", enhanced: "Smart quiet hours: suppress notifications during resident-defined sleep hours; daily summary digest option ('Your cleaner arrived at 9:02am and left at 11:45am') instead of per-event alerts", type: "AI (Notification Intelligence)", effort: "S", impact: "H", priority: "P1", owner: "Product" },
  { id: 31, name: "Staff Rating", current: "Resident rates staff after visit", enhanced: "Aggregate staff rating across all residents who share the same staff member; flag if rating drops below threshold; auto-suggest block/review to admin for low-rated staff", type: "AI (Aggregation + Alert)", effort: "S", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 32, name: "Selfie-Based Attendance", current: "Staff selfie for attendance marking", enhanced: "Integrate with HRMS (Darwinbox, Keka) for automatic payroll input; attendance data syncs to payroll module without manual export", type: "MCP (HRMS Integration)", effort: "M", impact: "H", priority: "P1", owner: "Integrations" },
  { id: 33, name: "Staff Roster Management", current: "Manual roster configuration for leaves and holidays", enhanced: "AI roster optimisation: suggests staffing adjustments based on historical occupancy patterns and community events (festival = more housekeeping needed); auto-notify replacements when leave approved", type: "AI (Roster Optimisation)", effort: "M", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 34, name: "Daily Helps — Payment & Recording", current: "Manual payment log", enhanced: "UPI payment directly from app to staff's UPI ID with auto-receipt; monthly payment summary for resident; expense log exportable to resident's own accounting", type: "MCP (UPI/Payment API)", effort: "S", impact: "H", priority: "P1", owner: "Integrations" },
  { id: 35, name: "Ticket Creation (Multi-Mode)", current: "Resident raises via app with photo/video", enhanced: "AI pre-classification: as resident types complaint, AI suggests category, sub-category, and relevant SOP; NLP analysis of audio note to auto-fill ticket fields; duplicate detection before submission", type: "AI (NLP + Classification)", effort: "M", impact: "VH", priority: "P0", owner: "AI Team" },
  { id: 36, name: "Priority Assignment", current: "Admin assigns priority manually", enhanced: "AI recommends priority based on: complaint type (water leak = high auto), number of similar tickets open, resident profile (golden ticket = auto-elevate), historical resolution time for category", type: "AI (Priority Recommendation)", effort: "S", impact: "VH", priority: "P0", owner: "AI Team" },
  { id: 37, name: "5-Layer Escalation Matrix (FM)", current: "Auto-escalation through 5 levels by time", enhanced: "AI-driven escalation: considers time of day, staff availability, and ticket complexity before escalating; 'smart pause' if technician is en route; WhatsApp escalation messages with direct resolve link", type: "AI + MCP (WhatsApp)", effort: "M", impact: "H", priority: "P0", owner: "Platform" },
  { id: 38, name: "TAT Calculation", current: "Calculated based on operational hours config", enhanced: "Real-time TAT tracking on resident-facing ticket view with progress bar ('Your issue is 65% through its SLA window'); traffic-light colour coding auto-applied", type: "Other", effort: "S", impact: "H", priority: "P1", owner: "Product" },
  { id: 39, name: "CAPA Reporting", current: "FM logs CAPA per ticket", enhanced: "AI generates CAPA template pre-filled with category, root cause options, and suggested actions based on similar past tickets; CAPA completion rate tracked in BI dashboard", type: "AI (CAPA Generation)", effort: "M", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 40, name: "Root Cause Analysis", current: "FM logs root cause manually", enhanced: "AI clusters recurring tickets by root cause automatically; monthly RCA report auto-generated showing top 5 systemic issues; links to asset health data for mechanical failures", type: "AI (Clustering + Report)", effort: "M", impact: "VH", priority: "P1", owner: "AI Team" },
  { id: 41, name: "Golden Ticket", current: "Admin flags vulnerable resident tickets", enhanced: "Auto-detection: if resident profile has 'senior citizen / differently-abled / pregnant' flag, all tickets auto-elevated to golden status; dedicated resolution queue in admin console", type: "Other (Profile Integration)", effort: "S", impact: "VH", priority: "P0", owner: "Product" },
  { id: 42, name: "Vendor Assignment", current: "Manual vendor assignment by admin", enhanced: "AI vendor recommendation: suggests best vendor based on category, location, past resolution score, current workload, and SLA track record; vendor accepts/declines via WhatsApp deep link", type: "AI + MCP (WhatsApp)", effort: "M", impact: "H", priority: "P0", owner: "AI Team" },
  { id: 43, name: "Ticket Feedback", current: "Resident rates resolution after closure", enhanced: "Sentiment analysis on feedback text; auto-flag tickets with negative sentiment even if star rating is 3+; monthly vendor sentiment report", type: "AI (Sentiment)", effort: "S", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 44, name: "Real-Time Analytical Report", current: "Live dashboard of ticket metrics", enhanced: "Natural language query: 'How many open plumbing tickets are older than 48 hours in Tower C?'; automated weekly digest email to FM head with top issues and trend lines", type: "AI (NLP Query)", effort: "M", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 45, name: "Rule-Based Auto Ticket Assignment", current: "Config-based routing rules", enhanced: "ML-based routing that improves over time: learns from historical assignment patterns and resolution outcomes to continuously optimise assignment accuracy beyond static rules", type: "AI (ML Routing)", effort: "H", impact: "VH", priority: "P0", owner: "AI Team" },
  { id: 46, name: "CAM Charges Configuration", current: "Admin manually configures charges per unit type", enhanced: "Template library: common CAM structures pre-loaded (e.g., RERA-compliant India templates, RERA UAE templates); AI validates configuration against regulatory norms before activation", type: "AI + MCP (RERA Templates)", effort: "S", impact: "H", priority: "P0", owner: "Product" },
  { id: 47, name: "Auto Invoice / Receipt Generation", current: "System-generated on billing cycle", enhanced: "WhatsApp invoice delivery: invoice auto-sent to resident's WhatsApp with pay-now link; AI detects when invoice is overdue and sends progressively firmer reminders with one-tap payment", type: "MCP (WhatsApp Business)", effort: "S", impact: "VH", priority: "P0", owner: "Integrations" },
  { id: 48, name: "Part / Full Payment", current: "Residents pay full or partial bill", enhanced: "AI payment nudge: suggests optimal partial payment amount based on resident's historical payment behaviour; 'Pay ₹2,000 now and clear remaining in 15 days' — improving collection rate", type: "AI (Payment Intelligence)", effort: "S", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 49, name: "Payment Gateway Support", current: "UPI, cards, net banking", enhanced: "Add BNPL (Buy Now Pay Later) option for large CAM bills via Simpl/LazyPay integration; auto-suggest EMI for bills above ₹10,000", type: "MCP (BNPL API)", effort: "S", impact: "H", priority: "P1", owner: "Integrations" },
  { id: 50, name: "ERP Export", current: "Manual export to ERP", enhanced: "Real-time bi-directional sync with Tally Prime via Tally Connector API; auto-post journal entries on payment receipt; reconciliation report in both systems", type: "MCP (Tally/SAP API)", effort: "H", impact: "VH", priority: "P1", owner: "Integrations" },
  { id: 51, name: "Defaulter Blocking", current: "Admin manually blocks defaulters", enhanced: "AI proactive intervention: 7 days before default threshold, AI sends personalised reminder with payment plan options; only blocks after reminder cycle — reducing defaulter rate without friction", type: "AI (Proactive Outreach)", effort: "S", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 52, name: "Offline Payment Reconciliation", current: "Manual entry for cash/cheque", enhanced: "OCR scanning of cheque image to auto-fill payment details; QR code cash receipt printable at admin console for resident acknowledgement", type: "AI (OCR)", effort: "S", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 53, name: "e-Notices with Attachments", current: "Admin creates and sends notices; read/unread tracked", enhanced: "AI draft assist: admin types subject and key points → AI generates full notice text; multi-language auto-translation to resident's preferred language; scheduled send with A/B test option", type: "AI (Draft + Translation)", effort: "M", impact: "H", priority: "P0", owner: "AI Team" },
  { id: 54, name: "Events (Create, RSVP, Like, Share)", current: "Admin creates events; residents RSVP", enhanced: "AI event timing recommendation: suggests best day/time based on historical resident engagement data; automated waitlist management; calendar sync (Google Calendar / iCal)", type: "AI + MCP (Calendar)", effort: "S", impact: "H", priority: "P1", owner: "Integrations" },
  { id: 55, name: "Polls", current: "Admin creates polls; residents vote", enhanced: "AI poll analysis: automatically identifies sentiment trend from free-text responses; generates executive summary of poll results for admin; schedule polls based on event triggers (post-maintenance completion satisfaction poll)", type: "AI (Analysis)", effort: "S", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 56, name: "Meeting (MoM)", current: "Admin logs MoM; auto-creates tasks", enhanced: "AI MoM assistant: admin records meeting audio → AI transcribes and extracts action items, owners, and deadlines automatically; draft MoM generated for admin review before send", type: "AI (Transcription + Extraction)", effort: "M", impact: "VH", priority: "P0", owner: "AI Team" },
  { id: 57, name: "Collaboration (Chat + Video)", current: "In-app chat and quick video calls", enhanced: "Threaded discussions by topic; AI summarises long chat threads; integration with project tasks (tag a task in chat, track status inline); end-to-end encryption", type: "AI + E2E Encryption", effort: "M", impact: "H", priority: "P1", owner: "Platform" },
  { id: 58, name: "Wellness Programs", current: "Admin configures webinar slots", enhanced: "Integration with Zoom/Google Meet for seamless video session launch from app; automated attendance tracking; session recording stored in document repository", type: "MCP (Zoom / Meet API)", effort: "S", impact: "M", priority: "P2", owner: "Integrations" },
  { id: 59, name: "Offers / Coupons", current: "Admin configures coupons for residents", enhanced: "AI personalised offer targeting: sends relevant offers based on resident engagement profile (gym user gets fitness offer, family with kids gets kids activity offer); A/B test offer effectiveness", type: "AI (Personalisation)", effort: "M", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 60, name: "Facility Booking", current: "Residents book amenities via app", enhanced: "AI demand forecasting: predicts peak booking periods and proactively opens additional slots; dynamic pricing option (peak hour surcharge); auto-waitlist with instant notification on cancellation", type: "AI (Demand Forecasting)", effort: "M", impact: "H", priority: "P0", owner: "AI Team" },
  { id: 61, name: "Sub-Facility Management", current: "Admin configures sub-areas", enhanced: "Interactive facility floor plan: resident selects specific court/lane/table on a visual map rather than a dropdown", type: "Other (UI Enhancement)", effort: "M", impact: "H", priority: "P1", owner: "Product" },
  { id: 62, name: "Club Membership Management", current: "Admin tracks membership and expiry", enhanced: "Auto-renewal via stored payment method with 30-day advance notice; membership tier upgrade recommendation based on usage patterns", type: "AI + Payment", effort: "S", impact: "H", priority: "P1", owner: "Product" },
  { id: 63, name: "Automated Usage-Based Charges", current: "Auto-billing on booking duration", enhanced: "Smart billing: differentiates between included-in-membership usage and chargeable overtime; sends micro-invoice on session end rather than monthly consolidated", type: "Other", effort: "S", impact: "H", priority: "P1", owner: "Product" },
  { id: 64, name: "PPM / AMC / Preparedness Checklists", current: "Digital checklists with QR/NFC dual control", enhanced: "AI-generated PPM schedules: input asset type + manufacturer specs → AI generates recommended PPM frequency and checklist; pre-built templates for common equipment (lifts, DG, STP)", type: "AI (Checklist Generation)", effort: "M", impact: "VH", priority: "P0", owner: "AI Team" },
  { id: 65, name: "Auto Task Assignment", current: "Config-based task routing", enhanced: "ML routing that learns from acceptance/rejection patterns; considers technician current workload, location, and skill certification for each task type", type: "AI (ML Assignment)", effort: "M", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 66, name: "QR/NFC + Supervisor Verification", current: "Dual control: field scan + supervisor verify", enhanced: "Geofenced verification: system confirms technician's GPS matches QR/NFC location before accepting scan; prevents remote scan forwarding; supervisor verification via WhatsApp approve link", type: "AI (Geo) + MCP (WhatsApp)", effort: "S", impact: "VH", priority: "P0", owner: "Platform" },
  { id: 67, name: "Soft Service Scheduling", current: "Admin schedules housekeeping, etc.", enhanced: "AI frequency optimisation: recommends service frequency based on community density, season, and past feedback scores; auto-adjusts after festive seasons for increased footfall", type: "AI", effort: "S", impact: "M", priority: "P2", owner: "AI Team" },
  { id: 68, name: "Asset Tagging & Registration", current: "QR code-based registration", enhanced: "Computer vision asset identification: photograph asset → AI identifies model, manufacturer, and retrieves spec sheet from knowledge base; pre-fills registration form automatically", type: "AI + CV", effort: "M", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 69, name: "Warranty / Guarantee Alerts", current: "Pre-expiry alerts for registered assets", enhanced: "Predictive alert: AI correlates warranty expiry with upcoming maintenance need; suggests whether to renew AMC or replace asset based on age and fault history", type: "AI", effort: "S", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 70, name: "Asset Maintenance Scheduling", current: "Manual scheduling", enhanced: "AI preventive maintenance predictor: analyses meter readings, fault history, and manufacturer guidance to predict optimal next maintenance window; reduces emergency breakdown by 40–60%", type: "AI (Predictive Maintenance)", effort: "H", impact: "VH", priority: "P0", owner: "AI Team" },
  { id: 71, name: "Meter Reading Logs", current: "Manual reading entry", enhanced: "IoT smart meter integration: auto-push readings via Modbus/MQTT; anomaly detection flags sudden consumption spikes (possible leak or theft) within 1-hour resolution", type: "IoT (Modbus/MQTT)", effort: "H", impact: "VH", priority: "P0", owner: "IoT Team" },
  { id: 72, name: "Min/Max Alert Levels", current: "Manual threshold config", enhanced: "AI adaptive thresholds: learns seasonal consumption patterns and adjusts alert thresholds dynamically (summer = higher water usage expected — threshold auto-adjusts)", type: "AI", effort: "S", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 73, name: "Utility Consumption Reports", current: "Monthly tower/meter reports", enhanced: "Benchmarking: compare consumption vs similar communities on platform (anonymised); identify outlier towers for energy audit; auto-generate ESG summary for developer annual report", type: "AI + Benchmarking", effort: "M", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 74, name: "PO / WO Management", current: "Manual PO/WO creation", enhanced: "Auto-generate PO from approved procurement request; digital PO sent to vendor via email/WhatsApp with acceptance link; vendor acknowledges digitally — no PDF email chains", type: "MCP (WhatsApp Business)", effort: "S", impact: "H", priority: "P1", owner: "Integrations" },
  { id: 75, name: "GRN / GDN Tracking", current: "Manual GRN/GDN entry", enhanced: "Supplier can submit GRN digitally via vendor portal link; OCR reads physical delivery note photo to auto-fill GRN form; auto-reconcile against PO quantities", type: "AI (OCR) + Vendor Portal", effort: "M", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 76, name: "Insufficient Stock Alerts", current: "Manual threshold + alert", enhanced: "ML demand forecasting: predicts stock depletion based on historical usage patterns and upcoming maintenance schedule; auto-triggers procurement request before stockout occurs", type: "AI (Forecasting)", effort: "M", impact: "VH", priority: "P1", owner: "AI Team" },
  { id: 77, name: "R&M Cost Tracking", current: "Manual cost entry per ticket", enhanced: "AI cost benchmarking: flags R&M costs that exceed similar jobs on platform (anonymised) by >20% for admin review; suggests alternative vendor if cost is persistently high", type: "AI + Benchmarking", effort: "M", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 78, name: "Multi-Layer Cost Approval", current: "Role-based config", enhanced: "WhatsApp approval chain: approvers receive approve/reject link in WhatsApp; no login required for approval; full audit trail maintained", type: "MCP (WhatsApp Business)", effort: "S", impact: "H", priority: "P0", owner: "Integrations" },
  { id: 79, name: "Permit to Work Checklist", current: "Digital PTW form completion", enhanced: "AI risk assessment: based on work type and location, AI pre-populates relevant hazard checklist items and required PPE; flags missing certification before work starts", type: "AI (Risk Assessment)", effort: "M", impact: "VH", priority: "P1", owner: "AI Team" },
  { id: 80, name: "Vendor Evaluation Checklist", current: "Manual fill + star rating", enhanced: "AI analysis of evaluation scores across all vendors: auto-generates vendor performance league table; alerts FM head when vendor score drops below threshold for consecutive evaluations", type: "AI (Analytics)", effort: "S", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 81, name: "Operational Audit Scheduling", current: "Admin assigns audit to community head", enhanced: "AI-generated audit checklist based on community type, previous audit findings, and regulatory requirements; predictive audit scheduling based on historical failure patterns", type: "AI (Audit Intelligence)", effort: "M", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 82, name: "Design Input Observation Report", current: "Manual observation entry with photos", enhanced: "AI snagging assistant: technician photographs defect → AI classifies defect type, severity, and affected area automatically; populates report fields and suggests remediation standard", type: "AI + CV", effort: "M", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 83, name: "Compliance Tracker", current: "Manual deadline entry + auto alerts", enhanced: "Regulatory calendar integration: auto-populate compliance deadlines from regulatory database (RERA, BIS, NBC, Dubai Building Code) based on community type; zero manual entry for standard deadlines", type: "MCP (Regulatory DB)", effort: "H", impact: "VH", priority: "P0", owner: "Integrations" },
  { id: 84, name: "Incident Reporting", current: "Multi-category form with voice note", enhanced: "AI incident categorisation: voice note auto-transcribed and categorised; CV analyses photo/video upload for incident type confirmation; auto-correlates with asset health data (was the DG under maintenance when fire occurred?)", type: "AI + CV", effort: "M", impact: "VH", priority: "P0", owner: "AI Team" },
  { id: 85, name: "Mailroom Inbound/Outbound", current: "Manual log + OTP delivery", enhanced: "Computer vision package identification: camera scans package label, auto-reads recipient name/unit from barcode/QR; resident notified with package photo; OTP auto-generated on delivery scan", type: "CV + AI (OCR)", effort: "M", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 86, name: "Package Delegation", current: "Resident nominates alternate collector", enhanced: "Time-limited delegation QR code sent to delegate's phone; OTP verification of delegate identity at collection; full audit trail in resident's account", type: "Other", effort: "S", impact: "M", priority: "P2", owner: "Product" },
  { id: 87, name: "Goods Movement Tracker", current: "Guard logs goods manually", enhanced: "ANPR vehicle link: goods entry auto-linked to registered vehicle plate; AI flags if goods type (e.g., furniture) doesn't match vehicle type (e.g., motorcycle); suspicious movement alert to admin", type: "AI + ANPR", effort: "M", impact: "H", priority: "P1", owner: "AI / Security" },
  { id: 88, name: "Waste Generation Tracking", current: "Manual waste entry", enhanced: "IoT bin sensors: smart bins auto-report weight/fill level; waste trend reports by type (dry/wet/hazardous); benchmarking vs similar communities; integration with BBMP/BMC collection schedules in India", type: "IoT + MCP (Municipal API)", effort: "H", impact: "M", priority: "P2", owner: "IoT Team" },
  { id: 89, name: "CCTV Surveillance Integration", current: "CCTV feeds connected to CV module", enhanced: "AI smart recording: trigger recording only on movement/anomaly detection; reduces storage by 80%; daily exception-only digest sent to security head instead of manual review", type: "AI (Smart Recording)", effort: "M", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 90, name: "Tailgating Detection", current: "CV detects tailgating at access points", enhanced: "Real-time alert under 2 seconds of detection; AI learns what 'normal two-person entry' looks like vs tailgating based on spacing, timing, and badge scan pattern", type: "AI (CV)", effort: "M", impact: "VH", priority: "P0", owner: "AI Team" },
  { id: 91, name: "ANPR", current: "Auto number plate recognition at gate", enhanced: "Edge-compute ANPR: processing on gate camera device (not cloud) for sub-1-second response; works in low light and partial plate obstruction; multi-country plate format support (India, UAE, Saudi)", type: "AI (Edge CV)", effort: "H", impact: "VH", priority: "P0", owner: "AI / Hardware" },
  { id: 92, name: "Heat Mapping (Occupancy)", current: "Real-time occupancy maps for common areas", enhanced: "Predictive occupancy: AI predicts peak times for each facility based on historical patterns; resident receives proactive notification 'Gym is likely quiet right now — perfect time to visit'", type: "AI (Predictive)", effort: "M", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 93, name: "Boom Barrier / Flap Barrier Integration", current: "API-based integration", enhanced: "Event-driven integration: barrier opens only after AI confirms vehicle plate matches registered list AND visitor/resident is verified; multi-factor before open; barrier open event triggers app notification to resident", type: "AI + Access Control", effort: "M", impact: "VH", priority: "P0", owner: "Integrations" },
  { id: 94, name: "IT-IoT Integration (API/ERP/OPC)", current: "Custom integration per project", enhanced: "Open integration framework: publish MCP server endpoints for all major protocols (REST, MQTT, Modbus, OPC-UA); self-service integration configuration in admin console for common systems", type: "MCP (Open Protocol)", effort: "VH", impact: "VH", priority: "P0", owner: "Platform" },
  { id: 95, name: "Lease Management", current: "Full lease module", enhanced: "AI lease expiry prediction: 90-day advance alert to owner with renewal negotiation support; auto-generate lease renewal draft based on market rate benchmarks; integration with property registration portals (India: IGRS)", type: "AI + MCP (Registry API)", effort: "H", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 96, name: "Space / Seat Management", current: "Book/cancel seats; floor plan view", enhanced: "AI desk allocation: learns team collaboration patterns and suggests adjacent seating for teams that frequently work together; ghost booking detection and auto-release after 15 min no-show", type: "AI (Collaboration Intelligence)", effort: "M", impact: "M", priority: "P2", owner: "AI Team" },
  { id: 97, name: "Transport Management System", current: "Bus/cab booking with tracking", enhanced: "Uber for Work / Ola Corporate API integration: one-tap booking from community app to corporate account; AI suggests optimal pick-up time based on historical commute patterns", type: "MCP (Ola/Uber API)", effort: "M", impact: "M", priority: "P2", owner: "Integrations" },
  { id: 98, name: "AQI Monitoring", current: "Real-time AQI map", enhanced: "Push notification when AQI crosses unhealthy threshold (>150 AQI); integration with IQAir or CPCB API for certified readings; weekly air quality report to developer for ESG reporting", type: "MCP (IQAir / CPCB API)", effort: "S", impact: "M", priority: "P2", owner: "Integrations" },
  { id: 99, name: "Self Health Declaration", current: "Resident submits health status", enhanced: "Remove as a mandatory daily feature (pandemic-era); repurpose as an optional wellness check-in with gamified health streak and wellness program recommendation based on responses", type: "AI (Personalisation)", effort: "S", impact: "L", priority: "P3", owner: "Product" },
  { id: 100, name: "B2B Health & Grocery Partnerships", current: "Integrated third-party partnerships", enhanced: "Build partner API catalogue: standardised integration contracts for Blinkit, Apollo Pharmacy, Practo, Urban Company; resident sees curated partner apps within Post Possession — not redirected to external app", type: "MCP (Partner APIs)", effort: "H", impact: "H", priority: "P1", owner: "Partnerships" },
  { id: 101, name: "HRMS Integration", current: "Sync with employee database", enhanced: "Bi-directional integration with Darwinbox, Keka, GreytHR via Webhooks; attendance data auto-posts to payroll; FM staff profile auto-created from HRMS onboarding event", type: "MCP (HRMS API)", effort: "M", impact: "H", priority: "P1", owner: "Integrations" },
  { id: 102, name: "White-Label Android App", current: "Developer-branded Android app", enhanced: "Dynamic theming engine: developer changes logo, colors, and splash screen from Admin Console in real time — no app store resubmission needed; supports Material You theming for Android 12+", type: "Other (Dynamic Theming)", effort: "H", impact: "VH", priority: "P0", owner: "Platform" },
  { id: 103, name: "White-Label iOS App", current: "Developer-branded iOS app", enhanced: "Same dynamic theming engine as Android; compliant with Apple App Store guidelines for white-label apps; developer can publish to their own App Store developer account with Lockated's toolchain", type: "Other (Dynamic Theming)", effort: "H", impact: "VH", priority: "P0", owner: "Platform" },
  { id: 104, name: "Rolling Banners", current: "Admin configures home screen banners", enhanced: "AI personalised banners: different banner shown to each resident segment (referral banner to high-engagement users; new project banner to residents in target geography for next launch)", type: "AI (Personalisation)", effort: "S", impact: "VH", priority: "P0", owner: "AI Team" },
  { id: 105, name: "Referral Marketing", current: "Resident refers friends; tracked in app", enhanced: "One-click share to WhatsApp/LinkedIn with pre-filled personalised referral message; real-time referral tracking dashboard for resident; AI identifies optimal timing to prompt referral (post positive feedback, post event attendance)", type: "AI + MCP (WhatsApp)", effort: "M", impact: "VH", priority: "P0", owner: "AI Team" },
  { id: 106, name: "New Project Updates", current: "Developer pushes project updates to residents", enhanced: "Segmented push: AI targets residents most likely to be interested in a new project based on property type, purchase history, engagement level, and geography; A/B test message variants", type: "AI (Segmentation)", effort: "S", impact: "VH", priority: "P0", owner: "AI Team" },
  { id: 107, name: "Customer Loyalty Program", current: "Points and rewards for engagement", enhanced: "AI loyalty engine: dynamic point multipliers based on resident engagement level; predictive churn alert when engagement drops — trigger retention reward automatically; gamified leaderboard for community", type: "AI (Loyalty Engine)", effort: "H", impact: "VH", priority: "P0", owner: "AI Team" },
  { id: 108, name: "Marketing Analytics", current: "Track campaign engagement and referral conversions", enhanced: "Funnel visualisation: referral impression → click → registration → site visit → booking; attribution model shows which community event or communication triggered the referral", type: "Other (Analytics)", effort: "M", impact: "VH", priority: "P0", owner: "Product" },
  { id: 109, name: "BI Reports — All Modules", current: "Detailed BI dashboards per module", enhanced: "Conversational BI: admin types 'Show me top 5 complaint categories in Tower B last month' → AI queries and renders chart inline; scheduled auto-email of key metrics to developer leadership", type: "AI (Conversational BI)", effort: "H", impact: "VH", priority: "P0", owner: "AI Team" },
  { id: 110, name: "Fitout Request", current: "Resident submits fitout request", enhanced: "AI fitout timeline predictor: based on scope of work, estimates completion time and flags common delays; automatic deviation detection by comparing submitted plans to approved structure", type: "AI", effort: "M", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 111, name: "Resident Unique QR Code", current: "QR for amenity access", enhanced: "Dynamic QR: code refreshes every 30 seconds to prevent sharing/screenshot access; integrates with turnstile/flap barrier hardware for physical access control", type: "Other (Security)", effort: "S", impact: "H", priority: "P1", owner: "Platform" },
  { id: 112, name: "Switch Flats (Multi-Flat)", current: "Context switch without re-login", enhanced: "Widget-based: iOS/Android widget shows quick status (visitors pending, new notices) for each unit without opening app; tap to switch context from lock screen", type: "Other (Widget)", effort: "S", impact: "H", priority: "P2", owner: "Mobile Team" },
  { id: 113, name: "Procurement (Request & Approval)", current: "Raise request; approval workflow; track consumption", enhanced: "AI demand forecasting: predicts procurement needs based on historical consumption and upcoming maintenance schedule; auto-generates procurement request 2 weeks before predicted stockout", type: "AI (Forecasting)", effort: "M", impact: "H", priority: "P1", owner: "AI Team" },
  { id: 114, name: "Parking Allocation", current: "Assign slots to residents", enhanced: "Visual parking map: admin and resident see real-time 3D-style parking map with colour-coded occupancy; resident claims their allocated slot from visual map", type: "Other (UI)", effort: "M", impact: "H", priority: "P1", owner: "Product" },
  { id: 115, name: "Vehicle Entry/Exit Management", current: "Log all vehicle movements", enhanced: "Computer vision + ANPR combined: vehicle auto-identified by plate AND make/model/colour confirmation to prevent plate cloning; alert if registered plate used on different vehicle body", type: "AI + CV + ANPR", effort: "H", impact: "VH", priority: "P0", owner: "AI / Security" },
  { id: 116, name: "Real-Time Parking View", current: "Live view of occupied/free slots", enhanced: "Predictive availability: AI predicts when slots will free up based on vehicle exit patterns (e.g., 'Slot B-12 likely free in 20 minutes — owner usually leaves at 9am'); push notification to waiting residents", type: "AI (Prediction)", effort: "M", impact: "H", priority: "P1", owner: "AI Team" },
];

const PostPossessionEnhancementsTab: React.FC = () => {
  const getRowColor = (type: string) => {
    if (type.toLowerCase().includes("ai") || type.toLowerCase().includes("ml") || type.toLowerCase().includes("nlp") || type.toLowerCase().includes("cv") || type.toLowerCase().includes("prediction") || type.toLowerCase().includes("classification") || type.toLowerCase().includes("generation") || type.toLowerCase().includes("analys") || type.toLowerCase().includes("personal")) return "bg-blue-50/50";
    if (type.toLowerCase().includes("mcp") || type.toLowerCase().includes("integration") || type.toLowerCase().includes("api")) return "bg-green-50/50";
    if (type.toLowerCase().includes("iot")) return "bg-orange-50/50";
    return "bg-white";
  };

  return (
    <div className="space-y-12 animate-fade-in font-poppins pb-10">
      {/* Header */}
      <div className="bg-white text-[#2C2C2C] border border-[#C4B89D] p-6 rounded-t-xl border-l-4 border-l-[#DA7756]">
        <h2 className="text-xl font-bold uppercase tracking-wider">
          Post Possession — Enhancement Roadmap
        </h2>
      </div>

      {/* Legend Block */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-2 mt-4">
        <div className="flex items-center gap-2 bg-blue-50/50 p-2 rounded-lg border border-blue-100">
          <div className="w-3 h-3 bg-blue-400 rounded-sm"></div>
          <span className="text-[10px] font-bold text-[#DA7756] uppercase tracking-tighter">AI-Powered</span>
        </div>
        <div className="flex items-center gap-2 bg-green-50/50 p-2 rounded-lg border border-green-100">
          <div className="w-3 h-3 bg-green-400 rounded-sm"></div>
          <span className="text-[10px] font-bold text-green-900 uppercase tracking-tighter">MCP Integrations</span>
        </div>
        <div className="flex items-center gap-2 bg-orange-50/50 p-2 rounded-lg border border-orange-100">
          <div className="w-3 h-3 bg-orange-400 rounded-sm"></div>
          <span className="text-[10px] font-bold text-orange-900 uppercase tracking-tighter">IoT Integrations</span>
        </div>
        <div className="flex items-center gap-2 bg-white p-2 rounded-lg border border-gray-100">
          <div className="w-3 h-3 bg-gray-300 rounded-sm"></div>
          <span className="text-[10px] font-bold text-gray-600 uppercase tracking-tighter">Other / UI / Platform</span>
        </div>
      </div>

      {/* Main Roadmap Table */}
      <div className="overflow-hidden border border-[#D3D1C7] rounded-xl shadow-lg bg-white mt-8">
        <table className="w-full border-collapse text-[11px] leading-relaxed">
          <thead>
            <tr className="bg-[#F6F4EE] text-[#2C2C2C] font-bold uppercase text-[9px] border-b border-[#D3D1C7] sticky top-0 z-10 shadow-sm">
              <th className="p-3 text-left w-[12%]">Feature Name</th>
              <th className="p-3 text-left w-[15%]">How It Currently Works</th>
              <th className="p-3 text-left w-[22%]">Enhanced Version</th>
              <th className="p-3 text-left w-[12%]">Integration Type</th>
              <th className="p-3 text-center w-[6%]">Effort</th>
              <th className="p-3 text-center w-[6%]">Impact</th>
              <th className="p-3 text-center w-[6%]">Priority</th>
              <th className="p-3 text-left w-[11%]">Owner</th>
            </tr>
          </thead>
          <tbody>
            {enhancements.map((item) => (
              <tr key={item.id} className={`border-b border-[#D3D1C7] last:border-0 hover:brightness-95 transition-all ${getRowColor(item.type)}`}>
                <td className="p-3 font-bold text-[#DA7756] align-top">{item.name}</td>
                <td className="p-3 text-gray-500 italic align-top">{item.current}</td>
                <td className="p-3 text-[#1a1a2e] font-medium align-top leading-normal">{item.enhanced}</td>
                <td className="p-3 align-top">
                  <span className="px-2 py-0.5 rounded-full bg-black/5 text-[9px] font-bold uppercase tracking-tighter text-gray-600 border border-black/5">
                    {item.type}
                  </span>
                </td>
                <td className="p-3 text-center align-top">
                  <span className={`font-bold ${item.effort === 'VH' ? 'text-red-600' : item.effort === 'H' ? 'text-orange-600' : 'text-gray-600'}`}>
                    {item.effort}
                  </span>
                </td>
                <td className="p-3 text-center align-top">
                  <span className={`font-bold ${item.impact === 'VH' ? 'text-green-600' : item.impact === 'H' ? 'text-blue-600' : 'text-gray-600'}`}>
                    {item.impact}
                  </span>
                </td>
                <td className="p-3 text-center align-top">
                  <span className={`px-2 py-1 rounded text-white font-black text-[9px] ${item.priority === 'P0' ? 'bg-red-700' : item.priority === 'P1' ? 'bg-blue-700' : 'bg-gray-400'}`}>
                    {item.priority}
                  </span>
                </td>
                <td className="p-3 text-[10px] text-gray-500 font-semibold align-top whitespace-nowrap">{item.owner}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default PostPossessionEnhancementsTab;

